sonar.projectKey=0carloscastillo0_Web-Portfolio-Carlos
sonar.organization=0carloscastillo0

# SonarCloud URL (cloud)
sonar.host.url=https://sonarcloud.io

# Sources frontend
sonar.sources=frontend-client/src

# Tests
sonar.tests=frontend-client/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

# Backend exluisions
sonar.exclusions=backend-api/**

# Coverage
sonar.javascript.lcov.reportPaths=frontend-client/coverage/lcov.info

sonar.sourceEncoding=UTF-8