import {
    SiJavascript,
    SiTypescript,
    SiPython,
    SiCss,
    SiHtml5,
    SiReact,
    SiVuedotjs,
    SiBootstrap,
    SiTailwindcss,
    SiNodedotjs,
    SiNestjs,
    SiDjango,
    SiSpringboot,
    SiPostgresql,
    SiMysql,
    SiMongodb,
    SiGit,
    SiGithub,
    SiLinux,
    SiDocker,
    SiPostman,
    SiVercel,
    SiTrello,
    SiJira,
    SiFigma,
} from "react-icons/si";
import { 
    FaJava, 
    FaAws 
} from "react-icons/fa";

export const skillIconMap = {
    typescript: SiTypescript,
    python: SiPython,
    java: FaJava,
    css3: SiCss,
    html5: SiHtml5,
    javascript: SiJavascript,
    react: SiReact,
    vue: SiVuedotjs,
    bootstrap: SiBootstrap,
    tailwindcss: SiTailwindcss,
    node: SiNodedotjs,
    nestjs: SiNestjs,
    django: SiDjango,
    springboot: SiSpringboot,
    postgresql: SiPostgresql,
    mysql: SiMysql,
    mongodb: SiMongodb,
    git: SiGit,
    github: SiGithub,
    linux: SiLinux,
    docker: SiDocker,
    postman: SiPostman,
    aws: FaAws,
    vercel: SiVercel,
    trello: SiTrello,
    jira: SiJira,
    figma: SiFigma
}