import {
    SiJavascript,
    SiTypescript,
    SiPython,
    SiCss,
    SiHtml5,
    SiReact,
    SiBootstrap,
    SiNodedotjs,
    SiNestjs,
    SiDjango,
    SiMysql,
    SiPostgresql,
    SiMongodb,
    SiGit,
    SiGithub,
    SiLinux,
    SiDocker,
    SiFigma,
} from "react-icons/si"

export const skillIconMap = {
    javascript: SiJavascript,
    typescript: SiTypescript,
    python: SiPython,
    css3: SiCss,
    html5: SiHtml5,
    react: SiReact,
    bootstrap: SiBootstrap,
    node: SiNodedotjs,
    nestjs: SiNestjs,
    django: SiDjango,
    mysql: SiMysql,
    postgresql: SiPostgresql,
    mongodb: SiMongodb,
    git: SiGit,
    github: SiGithub,
    linux: SiLinux,
    docker: SiDocker,
    figma: SiFigma
}