import type { Project } from "../portfolio.interface"

export const fallbackProjects: Project[] = [
  {
    id: "1",
    title: "Design and development of a CMS for the creation of websites about meeting management.",
    description: "• Led the design and development of a scalable SaaS-type CMS platform, facilitating the creation of personalized meeting websites by non-technical users. • The CMS was built with TypeScript, based on microfrontends (React) and integrating a REST API built with microservices (NestJS, Node.js), focused on domains and user-oriented. • Redesigned the NoSQL data model (MongoDB) with a dynamic and long-term maintainable approach. • Managed deployment in Cloud environments (Virtual Machine) with Docker (Docker Compose) controlled with GitHub (Git, CI/CD, SonarQube). • Reduced implementation time for new systems by 90%, automating creation for 3 meeting systems. • Decreased development effort for new meeting features by 60%.",
    startDate: "2024-08-05 00:00:00.000",
    endDate: "2025-07-18 00:00:00.000",
    coverImage: "/projects/project-cms-1.png",
    projectImages: [
      { id: "1", url: "/projects/project-cms-1.png", order: 0 },
      { id: "2", url: "/projects/project-cms-2.png", order: 1 },
      { id: "3", url: "/projects/project-cms-3.png", order: 2 },
      { id: "4", url: "/projects/project-cms-4.png", order: 3 },
    ],
    skills: [
      { id: "1", name: "TypeScript", category: "Language", icon: "typescript", level: "Advanced" },
      { id: "2", name: "CSS3", category: "Frontend", icon: "css", level: "Advanced" },
      { id: "3", name: "HTML5", category: "Frontend", icon: "html5", level: "Advanced" },
      { id: "4", name: "JavaScript", category: "Frontend", icon: "javascript", level: "Advanced" },
      { id: "5", name: "React", category: "Frontend", icon: "react", level: "Advanced" },
      { id: "6", name: "Node.js", category: "Backend", icon: "node", level: "Advanced" },
      { id: "7", name: "NestJS", category: "Backend", icon: "nestjs", level: "Intermediate" },
      { id: "8", name: "MongoDB", category: "Databases", icon: "mongodb", level: "Intermediate" },
      { id: "9", name: "Git", category: "Devops/Tools", icon: "git", level: "Advanced" },
      { id: "10", name: "GitHub", category: "Devops/Tools", icon: "github", level: "Advanced" },
      { id: "11", name: "Linux", category: "Devops/Tools", icon: "linux", level: "Intermediate" },
      { id: "12", name: "Docker", category: "Devops/Tools", icon: "docker", level: "Basic" },
      { id: "13", name: "Postman", category: "Devops/Tools", icon: "postman", level: "Advanced" },
      { id: "14", name: "Trello", category: "Project Management", icon: "trello", level: "Intermediate" },
      { id: "15", name: "Figma", category: "Design", icon: "figma", level: "Intermediate" },
    ]
  },
  {
    id: "2",
    title: "Public website maintenance.",
    description: "• Supported the maintenance of the company website (Django, Python), using the MVC pattern (models with PostgreSQL and views with HTML templates), with asynchronous communication between components (fetch). • Edited statistical charts (Chart.js), improving data visualization on the site. • Led the development of a new company video repository, achieving centralized audiovisual material and enabling public access. • Redesigned the user interface and navigation flow of the Whistleblower Channel, increasing critical complaint information visibility by 30%. • Resolved requirements from the company support system through documentation processes and continuous improvement.",
    startDate: "2025-01-06 00:00:00.000",
    endDate: "2025-02-21 00:00:00.000",
    coverImage: "/projects/project-web-4.png",
    projectImages: [
      { id: "1", url: "/projects/project-web-1.png", order: 0 },
      { id: "2", url: "/projects/project-web-2.png", order: 1 },
      { id: "3", url: "/projects/project-web-3.png", order: 2 },
      { id: "4", url: "/projects/project-web-4.png", order: 3 },
      { id: "5", url: "/projects/project-web-5.png", order: 4 },
    ],
    skills: [
      { id: "1", name: "Python", category: "Language", icon: "python", level: "Intermediate" },
      { id: "2", name: "HTML5", category: "Frontend", icon: "html5", level: "Advanced" },
      { id: "3", name: "CSS3", category: "Frontend", icon: "css", level: "Advanced" },
      { id: "4", name: "JavaScript", category: "Frontend", icon: "javascript", level: "Advanced" },
      { id: "5", name: "BootStrap", category: "Frontend", icon: "bootstrap", level: "Intermediate" },
      { id: "6", name: "Django", category: "Backend", icon: "django", level: "Intermediate" },
      { id: "7", name: "PostgreSQL", category: "Databases", icon: "postgresql", level: "Advanced" },
      { id: "8", name: "Git", category: "Devops/Tools", icon: "git", level: "Advanced" },
    ]
  },
  {
    id: "3",
    title: "Prototype of an advanced document management system.",
    description: "• Participated in the development of a desktop document management application, using advanced Python libraries and the MVC pattern. • The system allows managing documents locally or in the cloud (via Google Drive). • Collaborated in the implementation of an advanced search engine (using NLTK and PyPDF), achieving reduced search time for disorganized documents. • Collaborated in the implementation of a document classifier (using Scikit-Learn), using criteria of date, language, and topics, achieving automated organization. • Supported the implementation of an AI chatbot (using OpenAI), achieving systematization of information in documents.",
    startDate: "2023-08-28 00:00:00.000",
    endDate: "2023-12-22 00:00:00.000",
    coverImage: "/projects/project-docs-2.png",
    projectImages: [
      { id: "1", url: "/projects/project-docs-1.png", order: 0 },
      { id: "2", url: "/projects/project-docs-2.png", order: 1 },
      { id: "3", url: "/projects/project-docs-3.png", order: 2 },
      { id: "4", url: "/projects/project-docs-4.png", order: 3 },
    ],
    skills: [
      { id: "1", name: "Python", category: "Language", icon: "python", level: "Intermediate" },
      { id: "2", name: "GitHub", category: "Devops/Tools", icon: "github", level: "Advanced" },
      { id: "3", name: "Git", category: "Devops/Tools", icon: "git", level: "Advanced" },
      { id: "4", name: "Linux", category: "Devops / Tools", icon: "linux", level: "Intermediate" },
      { id: "5", name: "Jira", category: "Project Management", icon: "jira", level: "Basic" },
      { id: "6", name: "Figma", category: "Design", icon: "figma", level: "Intermediate" },
    ]
  },
  {
    id: "4",
    title: "Web interface for an educational system simulating mathematical exercises.",
    description: "• Collaborated in the development of an educational web application (using Scrum) to automate course management and simulate exercises on integers using a number line. • Supported the creation of metaphors for better understanding in simulated exercises. • Developed the user interface (Vue.js) of the entire system. • Integrated and consumed a REST API (Spring Boot) connected to an SQL database (PostgreSQL). • Reduced teacher workload by 30% in automated exercise generation.",
    startDate: "2023-03-06 00:00:00.000",
    endDate: "2023-08-04 00:00:00.000",
    coverImage: "/projects/project-math-1.png",
    projectImages: [
      { id: "1", url: "/projects/project-math-1.png", order: 0 },
      { id: "2", url: "/projects/project-math-2.png", order: 1 },
      { id: "3", url: "/projects/project-math-3.png", order: 2 },
    ],
    skills: [
      { id: "1", name: "Java", category: "Language", icon: "java", level: "Basic" },
      { id: "2", name: "HTML5", category: "Frontend", icon: "html5", level: "Advanced" },
      { id: "3", name: "Vue.js", category: "Frontend", icon: "vue", level: "Intermediate" },
      { id: "4", name: "BootStrap", category: "Frontend", icon: "bootstrap", level: "Intermediate" },
      { id: "5", name: "Spring Boot", category: "Backend", icon: "springboot", level: "Basic" },
      { id: "6", name: "PostgreSQL", category: "Databases", icon: "postgresql", level: "Advanced" },
      { id: "7", name: "Git", category: "Devops/Tools", icon: "git", level: "Advanced" },
      { id: "8", name: "GitHub", category: "Devops/Tools", icon: "github", level: "Advanced" },
      { id: "9", name: "Linux", category: "Devops/Tools", icon: "linux", level: "Intermediate" },
      { id: "10", name: "Docker", category: "Devops/Tools", icon: "docker", level: "Basic" },
      { id: "11", name: "Postman", category: "Devops/Tools", icon: "postman", level: "Advanced" },
      { id: "12", name: "Jira", category: "Project Management", icon: "jira", level: "Basic" },
      { id: "13", name: "Figma", category: "Design", icon: "figma", level: "Intermediate" },
    ]
  },
]