name: SonarCloud Frontend Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # sonar-scanner needs the full history to assign issues to commits

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Cache SonarCloud packages
      - name Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend-client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install only frontend deps
      - name: Install frontend deps
        working-directory: frontend-client
        run: npm install

      # Run test with coverage
      - name: Run tests
        working-directory: frontend-client
        run: npm run test:coverage

      # SonarCloud scan analyzing only frontend
      - name: SonarCloud Scan
        run: npx sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}