name: SonarCloud Frontend Analysis

on:
  push:
    branches:
      - feature/frontend
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # sonar-scanner needs the full history to assign issues to commits

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install only frontend deps
      - name: Install frontend deps
        run: |
          cd frontend-client
          npm install

      # Run test with coverage
      - name: Run tests
        run: |
          cd frontend-client
          npm run test:coverage

      # SonarCloud scan analyzing only frontend
      - name: SonarCloud Scan
        run: npx sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}